#!/bin/bash

# Validate user input
if [ "$#" -ne 3 ]; then
    echo "Please provide the input archive name and the number of combinatorial designs."
    echo "Example usage: ./run_puppeteer_lite HeadtoHead2.zip 40"
    exit 1
fi

# Run front-end
python3 loginview.py $1 $2

# Run back-end
curl -H "Content-Type: application/json" -d @request.json -X POST "http://128.31.25.45:8080/penguin-services-0.1.0/build" -o response.json

# Print gwl file
python3 tecan_json_to_gwl.py $1


echo 'Printed Tecan instructions.'
